name: Manage runner
run-name: terraform ${{ inputs.action }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      aws-access-key-id:
        required: True
      aws-secret-access-key:
        required: True
      aws-session-token:
        required: True
      cluster:
        description: "cluster name"
        type: choice
        options:
          - usgs-us-west-2
        default: usgs-us-west-2
      action:
        description: "cluster action"
        type: choice
        options:
          - apply
          - destroy

jobs:
  manage-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-session-token: ${{ inputs.aws-session-token }}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        #with:
        #  terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Terraform ${{ inputs.action}} $${{ inputs.cluster }}
        id: terraform-action
        working-directory: ./terraform/aws
        env:
          #TF_VAR_REGION: ${{ inputs.aws-region }}
          CLUSTER_CONFIG: ./bakeries/${{ inputs.cluster }}.tfvars
          ACTION: ${{ inputs.action }}
          #TF_LOG: INFO
          TF_INPUT: false
        run: |
          terraform init
          terraform  $ACTION -var-file=$CLUSTER_CONFIG -auto-approve
