name: Run recipe 
run-name: Run ${{ inputs.recipe_name }} from ${{ inputs.repo }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      aws_access_key_id:
        required: True
      aws_secret_access_key:
        required: True
      aws_session_token:
        required: True
      repo:
        description: 'The https github url for the recipe feedstock'
        required: true
      ref:
        description: 'The tag or branch to target in your recipe repo'
        required: true
        default: 'main'
      feedstock_subdir:
        description: 'The subdir of the feedstock directory in the repo'
        required: true
        default: 'feedstock'
      recipe_name:
        required: True
        default: recipe
      bucket:
        description: 'This job runner leverages s3fs.S3FileSystem for your recipe cache and output. Choices currently are: "default"'
        required: true
        default: 'default'
      prune:
        description: 'Only run the first two time steps'
        required: true
        default: '0'
      parallelism:
        description: 'Number of task managers to spin up'
        required: true
        default: '1'

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up aws credentials for job runner user
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-session-token: ${{ inputs.aws_session_token }}

      - name: install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: update kubeconfig with cluster
        run: |
          aws eks update-kubeconfig --name ${{ inputs.cluster_name }} --region ${{ inputs.aws_region }}

      - name: set up python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: install deps
        run: |
          pip install requirements.txt

      - name: run recipe
        run: |
          pangeo-forge-runner bake \
              --repo=$RECIPE_URL  \
              --ref="0.10.3" \
              -f config.py \
              --Bake.job_name=$RECIPE_NAME \
              --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
          AWS_SESSION_TOKEN: ${{ inputs.aws_session_token }}
          RECIPE_URL: ${{ inputs.recipe_url }}
          RECIPE_NAME: ${{ inputs.recipe_name}
