name: Validate Terraform
run-name: Validate Terraform by @${{ github.actor }}

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Terraform repo
        uses: actions/checkout@v3

      # Install the selected version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        #with:
        #  terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Terraform Validate
        id: validate
        working-directory: ./terraform/aws

        run: |
          terraform init -input=false -backend-config="KEY=VALUE"
          terraform validate
